import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, Boxes, PackagePlus, Wallet, FlaskConical } from "lucide-react";
import { useTranslation } from "react-i18next";
import { apiRequest } from "@/lib/queryClient";
import { useCurrency } from "@/hooks/use-currency";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

export default function Inventory() {
  const { t } = useTranslation(); const symbol = useCurrency((state) => state.getSymbol()); const { toast } = useToast(); const queryClient = useQueryClient();
  const [product, setProduct] = useState({ name: "", unit: "ml", currentQuantity: "0", reorderLevel: "0", unitCost: "0" });
  const [movement, setMovement] = useState({ productId: "", movementType: "receipt", quantity: "", productionCycleId: "", notes: "" });
  const { data: products = [] } = useQuery<any[]>({ queryKey: ["/api/inventory/products"] });
  const { data: summary } = useQuery<any>({ queryKey: ["/api/inventory/summary"] });
  const { data: movements = [] } = useQuery<any[]>({ queryKey: ["/api/inventory/movements"] });
  const { data: cycles = [] } = useQuery<any[]>({ queryKey: ["/api/production-cycles"] });
  const refresh = () => { queryClient.invalidateQueries({ queryKey: ["/api/inventory/products"] }); queryClient.invalidateQueries({ queryKey: ["/api/inventory/summary"] }); queryClient.invalidateQueries({ queryKey: ["/api/inventory/movements"] }); };
  const create = useMutation({ mutationFn: () => apiRequest("POST", "/api/inventory/products", product), onSuccess: () => { refresh(); setProduct({ name: "", unit: "ml", currentQuantity: "0", reorderLevel: "0", unitCost: "0" }); toast({ title: t("inventory_product_created", "Produit ajouté") }); }, onError: (error: Error) => toast({ title: t("error"), description: error.message, variant: "destructive" }) });
  const move = useMutation({ mutationFn: () => apiRequest("POST", `/api/inventory/products/${movement.productId}/movements`, { ...movement, productionCycleId: movement.productionCycleId || null }), onSuccess: () => { refresh(); setMovement({ productId: "", movementType: "receipt", quantity: "", productionCycleId: "", notes: "" }); toast({ title: t("inventory_movement_saved", "Mouvement enregistré") }); }, onError: (error: Error) => toast({ title: t("error"), description: error.message, variant: "destructive" }) });
  return <div className="space-y-6 page-fade-in" data-testid="inventory-page">
    <section className="rounded-2xl border bg-card p-5 shadow-sm"><div className="text-xs font-semibold uppercase tracking-[.18em] text-primary">{t("management", "Gestion")}</div><h1 className="mt-2 text-3xl font-bold text-[#082D5B]">{t("inventory", "Stocks & consommations")}</h1><p className="mt-1 text-sm text-muted-foreground">{t("inventory_subtitle", "Suivez les produits, seuils et consommations liés à la production.")}</p></section>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Boxes />} label={t("inventory_products", "Produits actifs")} value={summary?.productCount ?? 0}/><Metric icon={<AlertTriangle />} label={t("inventory_low_stock", "Sous le seuil")} value={summary?.lowStockCount ?? 0} danger={Number(summary?.lowStockCount||0)>0}/><Metric icon={<Wallet />} label={t("inventory_value", "Valeur du stock")} value={`${Number(summary?.stockValue||0).toLocaleString()} ${symbol}`}/><Metric icon={<FlaskConical />} label={t("inventory_month_consumption", "Consommation du mois")} value={`${Number(summary?.consumptionCostThisMonth||0).toLocaleString()} ${symbol}`}/></div>
    <div className="grid gap-5 xl:grid-cols-2">
      <Card><CardContent className="space-y-3 p-5"><h2 className="font-semibold text-[#082D5B]">{t("inventory_add_product", "Ajouter un produit")}</h2><div className="grid gap-3 sm:grid-cols-2"><Field label={t("name")} value={product.name} set={(v)=>setProduct({...product,name:v})}/><div><Label>{t("unit", "Unité")}</Label><Select value={product.unit} onValueChange={(v)=>setProduct({...product,unit:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["ml","l","g","kg","piece"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div><Field label={t("inventory_initial_quantity", "Quantité initiale")} type="number" value={product.currentQuantity} set={(v)=>setProduct({...product,currentQuantity:v})}/><Field label={t("inventory_reorder_level", "Seuil d’alerte")} type="number" value={product.reorderLevel} set={(v)=>setProduct({...product,reorderLevel:v})}/><Field label={t("inventory_unit_cost", "Coût unitaire")} type="number" value={product.unitCost} set={(v)=>setProduct({...product,unitCost:v})}/></div><Button disabled={!product.name||create.isPending} onClick={()=>create.mutate()}><PackagePlus className="mr-2 h-4 w-4"/>{t("add")}</Button></CardContent></Card>
      <Card><CardContent className="space-y-3 p-5"><h2 className="font-semibold text-[#082D5B]">{t("inventory_record_movement", "Enregistrer un mouvement")}</h2><div><Label>{t("product", "Produit")}</Label><Select value={movement.productId} onValueChange={(v)=>setMovement({...movement,productId:v})}><SelectTrigger><SelectValue placeholder={t("select")}/></SelectTrigger><SelectContent>{products.map(p=><SelectItem key={p.id} value={String(p.id)}>{p.name} · {Number(p.current_quantity).toLocaleString()} {p.unit}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-3 sm:grid-cols-2"><div><Label>{t("movement_type", "Type")}</Label><Select value={movement.movementType} onValueChange={(v)=>setMovement({...movement,movementType:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="receipt">{t("inventory_receipt", "Entrée")}</SelectItem><SelectItem value="consumption">{t("inventory_consumption", "Consommation")}</SelectItem><SelectItem value="adjustment">{t("inventory_adjustment", "Ajustement")}</SelectItem></SelectContent></Select></div><Field label={t("quantity")} type="number" value={movement.quantity} set={(v)=>setMovement({...movement,quantity:v})}/><div className="sm:col-span-2"><Label>{t("production_cycle_optional", "Cycle de production (optionnel)")}</Label><Select value={movement.productionCycleId||"none"} onValueChange={(v)=>setMovement({...movement,productionCycleId:v==="none"?"":v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">{t("none", "Aucun")}</SelectItem>{cycles.map(c=><SelectItem key={c.id} value={String(c.id)}>#{c.id} · {c.machineName} · {t(c.stage, c.stage)}</SelectItem>)}</SelectContent></Select></div></div><div><Label>{t("notes")}</Label><Textarea value={movement.notes} onChange={(e)=>setMovement({...movement,notes:e.target.value})}/></div><Button disabled={!movement.productId||!movement.quantity||move.isPending} onClick={()=>move.mutate()}>{t("save")}</Button></CardContent></Card>
    </div>
    <Card><CardContent className="p-0"><div className="hidden grid-cols-[2fr_1fr_1fr_1fr] gap-3 bg-[#082D5B] px-4 py-3 text-xs font-semibold uppercase text-white sm:grid"><span>{t("product")}</span><span>{t("stock")}</span><span>{t("inventory_reorder_level", "Seuil")}</span><span>{t("inventory_value", "Valeur")}</span></div>{products.map(p=><div key={p.id} className="grid gap-2 border-t px-4 py-3 sm:grid-cols-[2fr_1fr_1fr_1fr]"><strong>{p.name}</strong><span className={p.lowStock?"font-semibold text-red-700":""}>{Number(p.current_quantity).toLocaleString()} {p.unit}</span><span>{Number(p.reorder_level).toLocaleString()} {p.unit}</span><span>{Number(p.stockValue).toLocaleString()} {symbol}</span></div>)}</CardContent></Card>
    <Card><CardContent className="p-0"><div className="border-b px-4 py-3"><h2 className="font-semibold text-[#082D5B]">{t("inventory_recent_movements", "Mouvements récents")}</h2></div><div className="hidden grid-cols-[1.5fr_1fr_1fr_1fr] gap-3 bg-[#082D5B] px-4 py-3 text-xs font-semibold uppercase text-white sm:grid"><span>{t("product")}</span><span>{t("movement_type", "Type")}</span><span>{t("quantity")}</span><span>{t("date")}</span></div>{movements.map(m=><div key={m.id} className="grid gap-1 border-t px-4 py-3 text-sm sm:grid-cols-[1.5fr_1fr_1fr_1fr] sm:gap-3"><strong>{m.productName}</strong><span>{String(t(`inventory_${m.movementType}`, m.movementType))}</span><span className={Number(m.quantity)<0?"text-amber-700":"text-emerald-700"}>{Number(m.quantity)>0?"+":""}{Number(m.quantity).toLocaleString()} {m.unit}</span><span>{new Date(m.createdAt).toLocaleString()}</span></div>)}{movements.length===0&&<p className="p-6 text-center text-sm text-muted-foreground">{t("inventory_no_movements", "Aucun mouvement enregistré")}</p>}</CardContent></Card>
  </div>;
}
function Field({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <div><Label>{label}</Label><Input type={type} step={type==="number"?"0.000001":undefined} value={value} onChange={(e)=>set(e.target.value)}/></div>}
function Metric({icon,label,value,danger=false}:{icon:React.ReactNode;label:string;value:React.ReactNode;danger?:boolean}){return <Card><CardContent className="flex items-center gap-3 p-4"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${danger?"bg-red-100 text-red-700":"bg-primary/10 text-primary"}`}>{icon}</span><div><p className="text-xs text-muted-foreground">{label}</p><p className={`text-xl font-bold ${danger?"text-red-700":"text-[#082D5B]"}`}>{value}</p></div></CardContent></Card>}
