import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const receipt = readFileSync(join(root, "client/src/lib/receipt.ts"), "utf8");
const packageJson = readFileSync(join(root, "package.json"), "utf8");
const ordersPage = readFileSync(join(root, "client/src/pages/orders.tsx"), "utf8");
const orderDetailPage = readFileSync(join(root, "client/src/pages/order-detail.tsx"), "utf8");
const i18n = readFileSync(join(root, "client/src/lib/i18n.ts"), "utf8");
const paymentsPage = readFileSync(join(root, "client/src/pages/payments.tsx"), "utf8");
const storage = readFileSync(join(root, "server/storage.ts"), "utf8");
const schema = readFileSync(join(root, "shared/schema.ts"), "utf8");
const routes = readFileSync(join(root, "server/routes.ts"), "utf8");

assert.match(receipt, /const displayOrderId = orderDisplayId\(order\);/);
assert.match(receipt, /getReceiptContactLines\(settings, displayOrderId, lang\)/);
assert.match(receipt, /Registered by/);
assert.match(receipt, /Payment received by/);
assert.match(receipt, /agentFirstName\(payment\.agentName\)/);
assert.match(receipt, /function garmentItemTotal/);
assert.match(receipt, /function serviceItemTotal/);
assert.match(receipt, /function receiptRegisteredItemTotal/);
assert.match(receipt, /garments\.length > 0 \? garmentItemTotal\(garments\) : serviceItemTotal\(items\)/);
assert.match(receipt, /Total Registered Items/);
assert.match(receipt, /Unit Cost/);
assert.match(receipt, /Total Cost/);
assert.match(receipt, /colspan="4"/);
assert.match(receipt, /function receiptPrintCss/);
assert.match(receipt, /@page \{ size: A4; margin: 6mm; \}/);
assert.match(receipt, /print-color-adjust: exact/);
assert.match(receipt, /html\.pdf-export \.receipt/);
assert.match(receipt, /function downloadReceiptHtml/);
assert.match(receipt, /new Blob\(\[html\], \{ type: "text\/html;charset=utf-8" \}\)/);
assert.match(receipt, /import \{ domToPng \} from "modern-screenshot"/);
assert.match(receipt, /async function downloadReceiptImage/);
assert.match(receipt, /domToPng\(receipt/);
assert.match(receipt, /`deposit-receipt-order-\$\{displayOrderId\}\.png`/);
assert.match(receipt, /`payment-receipt-order-\$\{orderId\}\.png`/);
assert.match(packageJson, /"modern-screenshot"/);
assert.match(ordersPage, /watchedGarmentItems/);
assert.match(ordersPage, /totalRegisteredGarments/);
assert.match(ordersPage, /text-total-registered-garments/);
assert.match(orderDetailPage, /totalServicePieces/);
assert.match(orderDetailPage, /text-order-total-service-pieces/);
assert.match(orderDetailPage, /text-order-total-registered-garments/);
assert.match(i18n, /total_registered_items/);
assert.match(i18n, /total_pieces/);
assert.match(paymentsPage, /paymentId\?: number/);
assert.match(paymentsPage, /currentPayment\?\.collectedByEmployee\?\.name/);
assert.match(storage, /createdByEmployee: order\.createdByEmployeeId/);
assert.match(storage, /collectedByEmployee: payment\.collectedByEmployeeId/);
assert.match(schema, /PaymentWithEmployee/);
assert.doesNotMatch(receipt, /getReceiptContactLines\(settings, order\.id, lang\)/);
assert.doesNotMatch(receipt, /deposit-receipt-order-\$\{order\.id\}\.html/);
assert.doesNotMatch(receipt, /downloadReceiptHtml\(html, `deposit-receipt-order-\$\{displayOrderId\}\.html`\)/);
assert.doesNotMatch(receipt, /downloadReceiptHtml\(html, `payment-receipt-order-\$\{orderId\}\.html`\)/);
assert.doesNotMatch(receipt, /downloadReceiptPdfFromHtml/);
assert.doesNotMatch(receipt, /fetch\("\/api\/receipts\/render-pdf"/);
assert.doesNotMatch(receipt, /stripNoPrintElements\(html\)/);
assert.doesNotMatch(receipt, /deposit-receipt-order-\$\{displayOrderId\}\.pdf/);
assert.doesNotMatch(receipt, /payment-receipt-order-\$\{orderId\}\.pdf/);
assert.doesNotMatch(routes, /app\.post\("\/api\/receipts\/render-pdf"/);
assert.doesNotMatch(packageJson, /"puppeteer-core"/);
assert.doesNotMatch(packageJson, /"html2pdf\.js"/);
assert.doesNotMatch(receipt, /PDFDocument/);
assert.doesNotMatch(receipt, /pdf-lib/);
assert.doesNotMatch(packageJson, /"pdf-lib"/);

console.log("receipt display id regression tests passed");
